config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'items/index'
  devise_for :users

  root to: 'items#index'

  resources :users, only: [:show, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :user_parameters, if: :devise_controller?

  private

  def user_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      redirect_to action: "show"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<%= link_to 'マイページへ行く', user_path(current_user) %>
<div class="content">
  <% @items.each do |item| %> 
    <p>商品名：<%= item.name %></p>
    <p>値段：<%= item.price %>円</p>
    <p>説明文：<%=item.text%></p>
    <p>送料：<%=item.shipping_charges_id%></p>
    <p>配送地域：<%=item.prefectures_id%></p>
    <p>配送日数：<%=item.shipping_date_id%></p>
    <%= link_to '購入する'%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasypayApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="AccountPage">
  <div class="AccountPage__title">
    <h1>マイページ</h1>
  </div><br>
  <div class="Account__info">
    <h2>ユーザー情報</h2>
  </div>
  <div class="AccountPage__form">
    <%= form_for(current_user) do |f| %>
      <div class="FormField">
        <div class="FormField__name">
          <%= f.label :name %>
        </div>
        <div class="FormField__name">
          <%= f.text_field :name, autofocus: true %>
        </div>
      </div>
      <div class="FormField">
        <div class="FormField__email">
          <%= f.label :email %>
        </div>
        <div class="FormField__email">
          <%= f.email_field :email %>
        </div>
        <br>
      </div>
      <%= f.submit "更新する" %>
    <% end %>
    <br>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <br>
    <%= link_to "商品一覧へ戻る", root_path %>
  </div>
</div>